# Generated by Django 5.1 on 2024-09-11 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_todo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
