# Generated by Django 5.1 on 2024-09-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_todo_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_comleted',
            field=models.BooleanField(default=False),
        ),
    ]
