# Generated by Django 5.1 on 2024-09-12 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_todo_is_comleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_comleted',
            new_name='is_completed',
        ),
    ]
